# 공통 설정들
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    property-naming-strategy: LOWER_CAMEL_CASE
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  flyway:
    enabled: false

---

spring:
  profiles: development
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/storedb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: dongho135
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/storedb
    username: root
    password: dongho135
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1

# bind parameter 로깅 on
logging.level.org.hibernate.type.descriptor.sql: trace
logging.level.org.springframework.data.r2dbc: DEBUG
---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/storedb_test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: root
    password: dongho135
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
  r2dbc:
    url: r2dbc:pool:mysql://127.0.0.1:3306/storedb_test
    username: root
    password: dongho135
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
      validation-query: SELECT 1
# bind parameter 로깅 on
logging.level.org.hibernate.type.descriptor.sql: trace

---

spring:
  profiles: stage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
---

spring:
  profiles: production
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
